CREATE TABLE IF NOT EXISTS vlab_types (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    aap_start_job_template_id integer,
    aap_stop_job_template_id integer,
    aap_delete_job_template_id integer
);

ALTER TABLE vlab_types
ADD COLUMN IF NOT EXISTS aap_start_job_template_id integer;

ALTER TABLE vlab_types
ADD COLUMN IF NOT EXISTS aap_stop_job_template_id integer;

ALTER TABLE vlab_types
ADD COLUMN IF NOT EXISTS aap_delete_job_template_id integer;

ALTER TABLE vlab_types
ADD COLUMN IF NOT EXISTS aap_job_template_id integer;

UPDATE vlab_types
SET aap_start_job_template_id = COALESCE(aap_start_job_template_id, aap_job_template_id)
WHERE aap_job_template_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS vlabs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    type_id integer NOT NULL REFERENCES vlab_types (id),
    status text NOT NULL CHECK (status IN ('running', 'stopped', 'terminated', 'starting', 'stopping', 'deleting', 'failed')),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    aap_job_id integer,
    aap_target_status text CHECK (aap_target_status IN ('running', 'stopped', 'deleted') OR aap_target_status IS NULL),
    aap_last_job_status text
);

ALTER TABLE vlabs
DROP CONSTRAINT IF EXISTS vlabs_status_check;

UPDATE vlabs
SET status = CASE
    WHEN aap_target_status = 'stopped' THEN 'stopping'
    ELSE 'starting'
END
WHERE status = 'in_progress';

ALTER TABLE vlabs
ADD CONSTRAINT vlabs_status_check
CHECK (status IN ('running', 'stopped', 'terminated', 'starting', 'stopping', 'deleting', 'failed'));

ALTER TABLE vlabs
ADD COLUMN IF NOT EXISTS aap_job_id integer;

ALTER TABLE vlabs
ADD COLUMN IF NOT EXISTS aap_target_status text;

ALTER TABLE vlabs
DROP CONSTRAINT IF EXISTS vlabs_aap_target_status_check;

ALTER TABLE vlabs
ADD CONSTRAINT vlabs_aap_target_status_check
CHECK (aap_target_status IN ('running', 'stopped', 'deleted') OR aap_target_status IS NULL);

ALTER TABLE vlabs
ADD COLUMN IF NOT EXISTS aap_last_job_status text;

INSERT INTO vlab_types (name)
VALUES
    ('Airbus A320'),
    ('Airbus A380'),
    ('Boing 737')
ON CONFLICT (name) DO NOTHING;

UPDATE vlab_types
SET aap_start_job_template_id = seed.aap_start_job_template_id,
    aap_stop_job_template_id = seed.aap_stop_job_template_id,
    aap_delete_job_template_id = COALESCE(
        seed.aap_delete_job_template_id,
        vlab_types.aap_delete_job_template_id
    )
FROM (
    VALUES
        ('Airbus A320', 8, 18, 17),
        ('Airbus A380', 14, 18, 17),
        ('Boing 737', 10, 18, 17)
) AS seed(name, aap_start_job_template_id, aap_stop_job_template_id, aap_delete_job_template_id)
WHERE vlab_types.name = seed.name;

INSERT INTO vlabs (id, name, type_id, status, created_at)
SELECT seed.id, seed.name, types.id, seed.status, seed.created_at
FROM (
    VALUES
        (1, 'Flight controls validation', 'Airbus A320', 'running', CURRENT_TIMESTAMP - INTERVAL '4 days'),
        (2, 'Cabin systems training', 'Boing 737', 'stopped', CURRENT_TIMESTAMP - INTERVAL '5 days'),
        (3, 'Navigation sandbox', 'Embraer ERJ', 'running', CURRENT_TIMESTAMP - INTERVAL '6 days'),
        (4, 'Legacy test environment', 'Airbus A320', 'terminated', CURRENT_TIMESTAMP - INTERVAL '7 days')
) AS seed(id, name, type_name, status, created_at)
JOIN vlab_types AS types ON types.name = seed.type_name
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('vlabs', 'id'),
    COALESCE((SELECT MAX(id) FROM vlabs), 1),
    true
);
