CREATE TABLE IF NOT EXISTS vlab_types (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS vlabs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    type_id integer NOT NULL REFERENCES vlab_types (id),
    status text NOT NULL CHECK (status IN ('running', 'stopped', 'terminated')),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO vlab_types (name)
VALUES
    ('Airbus A320'),
    ('Boing 737'),
    ('Embraer ERJ')
ON CONFLICT (name) DO NOTHING;

INSERT INTO vlabs (id, name, type_id, status, created_at)
SELECT seed.id, seed.name, types.id, seed.status, seed.created_at
FROM (
    VALUES
        (1, 'Flight controls validation', 'Airbus A320', 'running', CURRENT_TIMESTAMP - INTERVAL '4 days'),
        (2, 'Cabin systems training', 'Boing 737', 'stopped', CURRENT_TIMESTAMP - INTERVAL '5 days'),
        (3, 'Navigation sandbox', 'Embraer ERJ', 'running', CURRENT_TIMESTAMP - INTERVAL '6 days'),
        (4, 'Legacy test environment', 'Airbus A320', 'terminated', CURRENT_TIMESTAMP - INTERVAL '7 days')
) AS seed(id, name, type_name, status, created_at)
JOIN vlab_types AS types ON types.name = seed.type_name
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('vlabs', 'id'),
    COALESCE((SELECT MAX(id) FROM vlabs), 1),
    true
);
