apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  labels:
    app: postgresql
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_DB: virtual_labs
  POSTGRES_USER: virtual_labs
  POSTGRES_PASSWORD: change-me
